import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import "./PageShell.css";

interface PageShellProps {
  eyebrow: string;
  title: string;
  subtitle?: string;
  children: ReactNode;
}

export function PageShell({ eyebrow, title, subtitle, children }: PageShellProps) {
  return (
    <div className="shell">
      <div className="shell__card">
        <header className="shell__header">
          <Link to="/" className="shell__eyebrow">
            {eyebrow}
          </Link>
          <h1 className="shell__title">{title}</h1>
          {subtitle && <p className="shell__subtitle">{subtitle}</p>}
        </header>
        <div className="shell__body">{children}</div>
      </div>
      <p className="shell__footnote">
        Estimates are generated by a machine-learning model trained on historical listings and are not a
        substitute for a professional appraisal.
      </p>
    </div>
  );
}
